# -*- coding: utf-8 -*-
"""kalman_trajectory_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IGBxe4ByuPeOYB0NVT0h3r79uRqHXbX
"""

import streamlit as st
import requests
import pandas as pd

st.title("Kalman Filter Tracker")

if "history" not in st.session_state:
    st.session_state.history = []

x = st.slider("X position", 0.0, 20.0, 10.0)
y = st.slider("Y position", 0.0, 20.0, 5.0)

if st.button("Send Measurement"):
    response = requests.post(
        "http://127.0.0.1:8000/predict",
        json={"x": x, "y": y}
    )

    if response.status_code == 200:
        result = response.json()

        st.session_state.history.append({
            "x": result["estimate_x"],
            "y": result["estimate_y"]
        })

        st.subheader("Estimate")
        st.write(f"X: {result['estimate_x']:.2f}")
        st.write(f"Y: {result['estimate_y']:.2f}")

        st.subheader("Velocity")
        st.write(f"Vx: {result['velocity_x']:.2f}")
        st.write(f"Vy: {result['velocity_y']:.2f}")

#Trajectory Plot
if st.session_state.history:
    df = pd.DataFrame(st.session_state.history)
    st.line_chart(df.rename(columns={"x": "X", "y": "Y"}))