# -*- coding: utf-8 -*-
"""kalman_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CgOBHNg77bt8TP3lfdyLjSO65ZG45sSH
"""

import numpy as np

class KalmanFilter2D:
    def __init__(self, dt=1.0):
        self.dt = dt

        self.F = np.array([
            [1, 0, dt, 0],
            [0, 1, 0, dt],
            [0, 0, 1, 0],
            [0, 0, 0, 1]
        ])

        self.H = np.array([
            [1, 0, 0, 0],
            [0, 1, 0, 0]
        ])

        self.Q = 0.01 * np.eye(4)
        self.R = 1.0 * np.eye(2)

        self.x = np.array([0, 0, 0, 0])  # state
        self.P = np.eye(4)

    def update(self, measurement):
        z = np.array(measurement)

        # Predict
        x_pred = self.F @ self.x
        P_pred = self.F @ self.P @ self.F.T + self.Q

        # Update
        y = z - self.H @ x_pred
        S = self.H @ P_pred @ self.H.T + self.R
        K = P_pred @ self.H.T @ np.linalg.inv(S)

        self.x = x_pred + K @ y
        self.P = (np.eye(4) - K @ self.H) @ P_pred

        return self.x