# -*- coding: utf-8 -*-
"""kalman_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKO9py_XIMjS_bDmF8frDExaqsFSNo0k
"""

from fastapi import FastAPI
from pydantic import BaseModel
from kalman import KalmanFilter2D

app = FastAPI()

kf = KalmanFilter2D()

class Measurement(BaseModel):
    x: float
    y: float

@app.post("/predict")
def predict(data: Measurement):
    state = kf.update([data.x, data.y])

    return {
        "estimate_x": float(state[0]),
        "estimate_y": float(state[1]),
        "velocity_x": float(state[2]),
        "velocity_y": float(state[3])
    }

@app.get("/state")
def get_state():
    return {
        "state": kf.x.tolist()
    }